// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPRIVWmg9NBSeQSvsmJSEp_9CGRLj0Z8',
    appId: '1:908304208416:web:3f2fec3631240000c0e245',
    messagingSenderId: '908304208416',
    projectId: 'quizz-app-7d3ec',
    authDomain: 'quizz-app-7d3ec.firebaseapp.com',
    storageBucket: 'quizz-app-7d3ec.appspot.com',
    measurementId: 'G-NDDLVLX8GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdt82FoHsS3rRSJwjGHq_zq-Piyq45l0',
    appId: '1:908304208416:android:affdfc2cbf9f295ac0e245',
    messagingSenderId: '908304208416',
    projectId: 'quizz-app-7d3ec',
    storageBucket: 'quizz-app-7d3ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARE-JTVhqM6qWlqsO3kApEWwOeMqeamP4',
    appId: '1:908304208416:ios:9f2ec0b08997b167c0e245',
    messagingSenderId: '908304208416',
    projectId: 'quizz-app-7d3ec',
    storageBucket: 'quizz-app-7d3ec.appspot.com',
    iosClientId: '908304208416-29jbmgrt6b4h3ccc29nkm9fk1ric29qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARE-JTVhqM6qWlqsO3kApEWwOeMqeamP4',
    appId: '1:908304208416:ios:9f2ec0b08997b167c0e245',
    messagingSenderId: '908304208416',
    projectId: 'quizz-app-7d3ec',
    storageBucket: 'quizz-app-7d3ec.appspot.com',
    iosClientId: '908304208416-29jbmgrt6b4h3ccc29nkm9fk1ric29qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );
}
